PRODUCT_COPY_FILES += \
    vendor/lge/bullhead/proprietary/bin/ATFWD-daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/ATFWD-daemon:lge \
    vendor/lge/bullhead/proprietary/bin/btnvtool:$(TARGET_COPY_OUT_SYSTEM)/bin/btnvtool:lge \
    vendor/lge/bullhead/proprietary/bin/cnd:$(TARGET_COPY_OUT_SYSTEM)/bin/cnd:lge \
    vendor/lge/bullhead/proprietary/bin/cnss-daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/cnss-daemon:lge \
    vendor/lge/bullhead/proprietary/bin/diag_klog:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_klog:lge \
    vendor/lge/bullhead/proprietary/bin/diag_mdlog:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_mdlog:lge \
    vendor/lge/bullhead/proprietary/bin/imsdatadaemon:$(TARGET_COPY_OUT_SYSTEM)/bin/imsdatadaemon:lge \
    vendor/lge/bullhead/proprietary/bin/imsqmidaemon:$(TARGET_COPY_OUT_SYSTEM)/bin/imsqmidaemon:lge \
    vendor/lge/bullhead/proprietary/bin/ims_rtp_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/ims_rtp_daemon:lge \
    vendor/lge/bullhead/proprietary/bin/irsc_util:$(TARGET_COPY_OUT_SYSTEM)/bin/irsc_util:lge \
    vendor/lge/bullhead/proprietary/bin/location-mq:$(TARGET_COPY_OUT_SYSTEM)/bin/location-mq:lge \
    vendor/lge/bullhead/proprietary/bin/loc_launcher:$(TARGET_COPY_OUT_SYSTEM)/bin/loc_launcher:lge \
    vendor/lge/bullhead/proprietary/bin/lowi-server:$(TARGET_COPY_OUT_SYSTEM)/bin/lowi-server:lge \
    vendor/lge/bullhead/proprietary/bin/msm_irqbalance:$(TARGET_COPY_OUT_SYSTEM)/bin/msm_irqbalance:lge \
    vendor/lge/bullhead/proprietary/bin/netmgrd:$(TARGET_COPY_OUT_SYSTEM)/bin/netmgrd:lge \
    vendor/lge/bullhead/proprietary/bin/nl_listener:$(TARGET_COPY_OUT_SYSTEM)/bin/nl_listener:lge \
    vendor/lge/bullhead/proprietary/bin/perfd:$(TARGET_COPY_OUT_SYSTEM)/bin/perfd:lge \
    vendor/lge/bullhead/proprietary/bin/pm-proxy:$(TARGET_COPY_OUT_SYSTEM)/bin/pm-proxy:lge \
    vendor/lge/bullhead/proprietary/bin/pm-service:$(TARGET_COPY_OUT_SYSTEM)/bin/pm-service:lge \
    vendor/lge/bullhead/proprietary/bin/port-bridge:$(TARGET_COPY_OUT_SYSTEM)/bin/port-bridge:lge \
    vendor/lge/bullhead/proprietary/bin/qmakernote-xtract:$(TARGET_COPY_OUT_SYSTEM)/bin/qmakernote-xtract:lge \
    vendor/lge/bullhead/proprietary/bin/qmuxd:$(TARGET_COPY_OUT_SYSTEM)/bin/qmuxd:lge \
    vendor/lge/bullhead/proprietary/bin/radish:$(TARGET_COPY_OUT_SYSTEM)/bin/radish:lge \
    vendor/lge/bullhead/proprietary/bin/rmt_storage:$(TARGET_COPY_OUT_SYSTEM)/bin/rmt_storage:lge \
    vendor/lge/bullhead/proprietary/bin/subsystem_ramdump:$(TARGET_COPY_OUT_SYSTEM)/bin/subsystem_ramdump:lge \
    vendor/lge/bullhead/proprietary/bin/thermal-engine:$(TARGET_COPY_OUT_SYSTEM)/bin/thermal-engine:lge \
    vendor/lge/bullhead/proprietary/bin/time_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/time_daemon:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_General_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Global_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Handset_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Headset_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/cne/profile.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/profile.txt:lge \
    vendor/lge/bullhead/proprietary/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/dsi_config.xml:lge \
    vendor/lge/bullhead/proprietary/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/netmgr_config.xml:lge \
    vendor/lge/bullhead/proprietary/etc/data/qmi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/qmi_config.xml:lge \
    vendor/lge/bullhead/proprietary/etc/flp.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/flp.conf:lge \
    vendor/lge/bullhead/proprietary/etc/izat.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/izat.conf:lge \
    vendor/lge/bullhead/proprietary/etc/lowi.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/lowi.conf:lge \
    vendor/lge/bullhead/proprietary/etc/old-apns-conf.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/old-apns-conf.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/cneapiclient.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/cneapiclient.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/com.android.omadm.service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.android.omadm.service.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/com.android.sdm.plugins.connmo.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.android.sdm.plugins.connmo.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/com.android.sdm.plugins.sprintdm.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.android.sdm.plugins.sprintdm.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/privapp-permissions-bullhead.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-bullhead.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/privapp-permissions-google.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-google.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_permissions.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/rcsservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/rcsservice.xml:lge \
    vendor/lge/bullhead/proprietary/etc/qcril.db:$(TARGET_COPY_OUT_SYSTEM)/etc/qcril.db:lge \
    vendor/lge/bullhead/proprietary/etc/sap.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/sap.conf:lge \
    vendor/lge/bullhead/proprietary/etc/sysconfig/bullhead_common.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/bullhead_common.xml:lge \
    vendor/lge/bullhead/proprietary/etc/sysconfig/google_build.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/google_build.xml:lge \
    vendor/lge/bullhead/proprietary/etc/sysconfig/google.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/google.xml:lge \
    vendor/lge/bullhead/proprietary/etc/sysconfig/whitelist_com.android.omadm.service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/whitelist_com.android.omadm.service.xml:lge \
    vendor/lge/bullhead/proprietary/etc/thermal-engine-8992.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/thermal-engine-8992.conf:lge \
    vendor/lge/bullhead/proprietary/lib64/hw/gps.msm8992.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/gps.msm8992.so:lge \
    vendor/lge/bullhead/proprietary/lib64/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgps.utils.so:lge \
    vendor/lge/bullhead/proprietary/lib64/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_core.so:lge \
    vendor/lge/bullhead/proprietary/lib64/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_eng.so:lge \
    vendor/lge/bullhead/proprietary/lib/hw/gps.msm8992.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.msm8992.so:lge \
    vendor/lge/bullhead/proprietary/lib/libdmengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmengine.so:lge \
    vendor/lge/bullhead/proprietary/lib/libdmjavaplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmjavaplugin.so:lge \
    vendor/lge/bullhead/proprietary/lib/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgps.utils.so:lge \
    vendor/lge/bullhead/proprietary/lib/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_core.so:lge \
    vendor/lge/bullhead/proprietary/lib/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_eng.so:lge \


PRODUCT_COPY_FILES += \
    vendor/lge/bullhead/proprietary/lib/libdmjavaplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmjavaplugin.so:lge \
    vendor/lge/bullhead/proprietary/lib/libdmengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmengine.so:lge

